name: tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, dev, simplify ]
  pull_request:
    branches: [ master ]




# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nimversion:
        - stable
        - devel

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'

    - uses: iffy/install-nim@v1.1
      with:
        nimversion: ${{ matrix.nimversion }}

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: actions-rs/cargo@v1

    - name : install d4
      run: |
        export HTSLIB=dynamic
        sudo apt-get update
        sudo apt-get install git llvm curl wget libcurl4-openssl-dev
        wget https://github.com/samtools/htslib/archive/1.11.tar.gz
        tar xzf 1.11.tar.gz
        cd htslib-1.11/
        sudo make -j4 install
        git clone https://github.com/38/d4-format
        cd d4-format
        cargo build --release
        sudo cp ../d4-format/target/release/libd4binding.* /usr/local/lib
        sudo cp ./d4binding/include/d4.h /usr/local/include/

    # Runs a single command using the runners shell
    - name: test nim stuff
      run: |
        export LD_LIBRARY_PATH=/usr/local/lib/
        nimble build -y
        nimble test

    # Runs a set of commands using the runners shell
    - name: test javascript stuff
      run: |
        npm install mocha
        npm test


